export type Patient = {
  active: boolean;
  address: string | null;
  address_number: string | null;
  birthday: string | null;
  complement: string | null;
  cpf: string;
  created_at: string;
  email: string | null;
  expiration_plan: string | null;
  gender: string | null;
  health_plan: string | null;
  idpatient: string;
  name: string;
  neighborhood: string | null;
  number_plan: string | null;
  phone: string;
  search: string;
  updated_at: string;
  zip_code: string | null;
};
